---
title: "Компьютерная математика"
subtitle: "Описание и программа курса"
author: "Храмов Д.А."
date: "27.02.2019"
output: 
  html_document:
    toc: true
---


Курс посвящен освоению MATLAB — пакета программирования для научных и инженерных расчетов. Основными преимуществами MATLAB являются:

* возможность создавать компактный программный код за счет операций над массивом в целом;
* богатейшая коллекция готовых функций;
* развитые графические возможности. MATLAB позволяет построить двух- или трехмерный график полиграфического качества с помощью всего одной функции.

Наш курс является базой для освоения других курсов направления "научные вычисления" (scientific computing).

**Материалы курса:** https://github.com/dkhramov/km_2019


## 1. Знакомство с MATLAB

Что такое научные вычисления. Основные преимущества MATLAB. Интерфейс MATLAB. Операции и приоритет. Переменные, роль ";". Типы данных. Матрицы. Обращение к элементам. Поэлементные операции. Элементарные функции. Оператор ":". Построение графиков. Решение уравнения графическим способом. Бесплатная альтернатива MATLAB. Информационные ресурсы по MATLAB.

**Задачи:** Допустимые имена переменных. Предельная скорость спуска парашютиста. Операции со строками. Поиск корней уравнения графическим способом.


## 2. Массивы. Логическая индексация

Задание массивов. Массивы-строки и массивы-столбцы. Обращение к элементам массива. Многомерные массивы. Функции для создания массивов. Сообщения об ошибках.

Векторизация циклов. Логическая индексация элементов массива.


## 3. Управление вычислительным процессом. Двумерная графика

Виды вычислительных процессов. Условный оператор. Логические условия. Функции составления скалярных условий. Оператор множественного выбора switch. Циклы for и while. Вложенные циклы. Экстренный выход из цикла.

Функция plot. Цвет линии, тип линии, маркеры точек. Построение нескольких графиков одновременно. Сетка. Вывод текста в графическом окне. Графические объекты: окно, координатные оси, линии. Специальные графики. Логарифмический масштаб. Полярные координаты.


## 4. Функции. Ввод/вывод

Фрагменты скриптов. Функции. Передача параметров: формальные и фактические параметры. Отладка функций. Локальные и глобальные переменные. Подфункции (субфункции). Объединение набора скалярных параметров в массив. Анонимные функции (однострочники). Проверка аргументов функций.

Ввод данных с клавиатуры и из графического окна. Ввод/вывод данных в текстовые файлы. Форматированный ввод/вывод. Массив строк. Операции над файлами. Сохранение/загрузка рабочей среды (save, load).


## 5. Векторная алгебра. Трехмерная графика

Вектор. Система координат. Норма вектора. Скалярное и векторное произведения. Координаты вектора в разных системах координат. Перенос. Связь новых координат со старыми. Поворот. Формулы для пересчета старых координат в новые. Матрица преобразования координат. Масштабирование. Отражение. Последовательные преобразования. Однородные координаты. Некоммутативность умножения матриц. Обратное преобразование.

Трехмерная графика. Построение графиков кривых и точек в пространстве. Поверхность в трехмерном пространстве. Как задать область определения: meshgrid. Построение графиков функций двух переменных: mesh, surf. Вспомогательные графические функции


## 6. Особенности компьютерной арифметики. Символьные расчеты

Математический объект и его Компьютерная реализация. Вещественные числа с плавающей точкой. Мантисса и порядок. Расстояние между соседними числами. Машинный эпсилон. Следствия использования чисел с плавающей точкой.

Символьные расчеты. Создание символьных объектов. Решение уравнений и систем. 

Математический Анализ: пределы, производные, интегралы, суммирование рядов, разложение в ряд Тейлора. 

Арифметика заданной точности.

Преобразование и упрощение выражений. Замена выражений. Системы компьютерной математики.


## 7. Решение уравнений

Поиск корней полиномов (roots). Комплексные корни. Поиск действительных корней уравнений (fzero). 

Системы линейных уравнений. Графическая интерпретация решения. Число решений системы. Вырожденные случаи. Детерминант. Плохо обусловленные системы.


## 8. Исследование функций

Поиск максимумов и минимумов функций. Точки перегиба.


## 9. Графические объекты. Работа с изображениями и видео

Иерархия типов данных. Иерархия графических объектов. Дескрипторная графика. Динамическое построение графиков.

Изображение. Чтение и запись изображения. Множество Жюлиа и Мандельброта. Игра "Жизнь".

Работа с видео. Захват изображения. Воспроизведение и сохранение видео.


## 10. Эффективное программирование

Типичные ошибки. Увеличение скорости или экономия памяти? Оценка быстродействия алгоритма.


## Литература

1. Ануфриев И. Е., Смирнов А. Б., Смирнова Е. Н. MATLAB 7. - СПб.: БХВ-Петербург. 2005.
2. Хант Б. и др. Matlab R2007 с нуля! - М.: Лучшие книги, 2008.
3. MatLab. Язык технических вычислений. Вычисление, визуализация, программирование / Пер. с англ. Конюшенко В.В.

